[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


remappings = [
"ds-test/=lib/forge-std/lib/ds-test/src/",
"erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
"forge-std/=lib/forge-std/src/",
"wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
"@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]
